[[profile]]
name = "docked"
exec = []
	# Primary Monitor
	[[profile.output]]
	enable = true
	search = ["m=M27Q", "s=24020B003742", "v=GIGA-BYTE TECHNOLOGY CO., LTD."]
	mode = "2560x1440@164.998Hz"
	position = "0,0"
	scale = 1.0
	transform = "normal"
	adaptive_sync = true
	exec = []

	# Secondary Monitor
	[[profile.output]]
	enable = true
	search = ["m=PHL 241E1", "s=0x00000247", "v=Philips Consumer Electronics Company"]
	mode = "1920x1080@74.973Hz"
	position = "2560,130"
	scale = 1.0
	transform = "normal"
	adaptive_sync = true
	exec = []

	# Built-in Monitor
	[[profile.output]]
	enable = false
	search = ["m=0x095F", "s=", "v=BOE"]
	mode = "2256x1504@59.999Hz"
	position = "0,1440"
	scale = 1.0
	transform = "normal"
	adaptive_sync = true
	exec = []

[[profile]]
name = "laptop"
exec = []
	# Built-in Monitor
	[[profile.output]]
	enable = true
	search = ["m=0x095F", "s=", "v=BOE"]
	mode = "2256x1504@59.999Hz"
	position = "0,0"
	scale = 1.35
	transform = "normal"
	adaptive_sync = true
	exec = []
